### ISSUE TITLE
"intor" au lieu de "intro" 

### ISSUE THREAD

**Issue by g-ongenae** [alx/gitbook#10]
Bonjour,

En allant sur votre la version de votre [site](http://alexgirard.com/git-book/index.html) le lien vers la page bienvenue sur git à une erreur de frappe. Je n'ai pas trouvé où faire la correction.

![Erreur de frappe](https://user-images.githubusercontent.com/9453090/34908598-1602c15a-f88a-11e7-88ea-7f3b02288c43.png)

Aussi, j'ai remarqué que le lien ne retourne pas une 404 mais reviens sur la même page (avec le lien cassé, ce qui casse tous les autres).

**Comment by alx** [comment]
Bonjour,

Merci pour ce retour.

Ça fait un moment que je n'ai pas relancé la génération des fichiers du site à partir de ce repo git, du coup j'ai corrigé la typo directement sur le serveur web.

Bonn journée,

Alex
